name: Code Quality

on:
  pull_request:

defaults:
  run:
    shell: bash -el {0}

jobs:
  ruff:
    name: Linting & Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      # Check for linting issues
      - name: Check Linting
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0
        with:
          args: "check"

      # Check for correct formatting
      - name: Check Formatting
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b #v4.0.0
        with:
          args: "format --check --diff"