name: Test

on:
  pull_request:

defaults:
  run:
    shell: bash -el {0}

jobs:
  unit:
    name: Unit Tests
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26, macos-26-intel]
        python: [3.11, 3.13]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          activate-environment: pytest-indigo-dev
          environment-file: environment.yaml
          python-version: ${{ matrix.python }}
          auto-activate: false
      
      - name: Test
        run: pytest
